version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Download Terraform
          command: |
            wget https://dl.bintray.com/mitchellh/terraform/terraform_0.11.7_linux_amd64.zip
            unzip terraform_0.11.7_linux_amd64.zip
      - run:
          name: Terraform Sync Config
          command: |
             ./terraform remote config -backend=S3 -backend-config="bucket=$BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
            # ./terraform plan -out=terraform.plan

  # deployment:
  #   production:
  #     branch: master
  #     commands:
  #       - ./terraform apply terraform.plan
  #       - ./terraform remote push