version: 2
jobs:
  build:
    docker:
      - image: python:2.7.14-jessie
    steps:
      - checkout
      - run:
          name: OS Update
          command: |
            apt-get update
            apt-get install -y wget unzip
            pip install awscli
            pip install aliyuncli
      - run:
          name: Download Terraform
          command: |
            wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            unzip terraform_0.11.7_linux_amd64.zip
      - run:
          name: Terraform Sync Config
          command: |
             ./terraform remote config -backend=S3 -backend-config="bucket=$BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
            # ./terraform plan -out=terraform.plan

  # deployment:
  #   production:
  #     branch: master
  #     commands:
  #       - ./terraform apply terraform.plan
  #       - ./terraform remote push